default:
  adapter: postgresql
  host: localhost

development:
  adapter: postgresql
  host: localhost
  datamapper_adapter: postgres
  database: redcap2omop_demo
  username: redcap2omop_demo
  password: redcap2omop_demo
